//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.208
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTimeSheet.TimeSheetService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TimeSheetService.ITimeSheetService")]
    public interface ITimeSheetService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimeSheetService/GetData", ReplyAction="http://tempuri.org/ITimeSheetService/GetDataResponse")]
        string[] GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimeSheetService/UpdateData", ReplyAction="http://tempuri.org/ITimeSheetService/UpdateDataResponse")]
        int UpdateData(int id, string name, string summary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimeSheetService/GetDetailData", ReplyAction="http://tempuri.org/ITimeSheetService/GetDetailDataResponse")]
        string[] GetDetailData(int week, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimeSheetService/SubmitData", ReplyAction="http://tempuri.org/ITimeSheetService/SubmitDataResponse")]
        int SubmitData(int week, string name, string pic, string ps, string time, int pid, string text, double hours);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimeSheetService/UpdateDetailData", ReplyAction="http://tempuri.org/ITimeSheetService/UpdateDetailDataResponse")]
        int UpdateDetailData(int week, string name, int pid, string text, double hours, int uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimeSheetService/DeleteDetailDate", ReplyAction="http://tempuri.org/ITimeSheetService/DeleteDetailDateResponse")]
        void DeleteDetailDate(int week, string name, int uid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITimeSheetServiceChannel : MyTimeSheet.TimeSheetService.ITimeSheetService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TimeSheetServiceClient : System.ServiceModel.ClientBase<MyTimeSheet.TimeSheetService.ITimeSheetService>, MyTimeSheet.TimeSheetService.ITimeSheetService {
        
        public TimeSheetServiceClient() {
        }
        
        public TimeSheetServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TimeSheetServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimeSheetServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimeSheetServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public int UpdateData(int id, string name, string summary) {
            return base.Channel.UpdateData(id, name, summary);
        }
        
        public string[] GetDetailData(int week, string username) {
            return base.Channel.GetDetailData(week, username);
        }
        
        public int SubmitData(int week, string name, string pic, string ps, string time, int pid, string text, double hours) {
            return base.Channel.SubmitData(week, name, pic, ps, time, pid, text, hours);
        }
        
        public int UpdateDetailData(int week, string name, int pid, string text, double hours, int uid) {
            return base.Channel.UpdateDetailData(week, name, pid, text, hours, uid);
        }
        
        public void DeleteDetailDate(int week, string name, int uid) {
            base.Channel.DeleteDetailDate(week, name, uid);
        }
    }
}
